# Generated by Django 3.2.5 on 2021-09-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_Student_Data_For_Dashboard_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=100)),
                ('TotalStudents', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Class_Student_Data',
            },
        ),
        migrations.AlterField(
            model_name='add_assignment_model',
            name='AddedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignment_marks_model',
            name='Marks',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='fill_assignment_report_model',
            name='AddedBy',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AlterField(
            model_name='fill_assignment_report_model',
            name='AddedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
